---
DATADOG_API_KEY: "SPECIFY_KEY_HERE"

datadog_agent_version: ''

datadog_apt_key: "A2923DFF56EDA6E76E55E492D3A80E30382E94DE"
datadog_debian_pkgs:
  - apparmor-utils
  - build-essential
  - curl
  - g++
  - gcc
  - ipython
  - pkg-config
  - rsyslog

DATADOG_ENV: 'unknown'
DATADOG_GROUP: 'unknown'
