---
#
# datadog
#
# Overview:
#
# Installs datadog
##
# Dependencies:
#
# Example play:
#   roles:
#   - common
#   - datadog
#
- include: install.yml
  when: COMMON_ENABLE_DATADOG
  tags:
    - datadog

- include: uninstall.yml
  when: not COMMON_ENABLE_DATADOG
  tags:
    - datadog
