---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role server_utils
# 
# Overview:
#
# Install useful interactive utilities for triange and debugging purposes.
# Typically these would not need to be available on servers as shell access
# is uneccessary.
# 
# Example play:
#
#

- name: Update expired rabbitmq repo key
  shell: "curl -L https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey | apt-key add -"
  args:
    warn: False

- name: Update expired edX PPA repo key
  shell: "apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 69464050 ; apt-key update ; apt-get update"
  args:
    warn: False

- name: Install ubuntu system packages
  apt:
    name: "{{ item }}"
    install_recommends: yes
    state: present 
    update_cache: yes
  with_items: "{{ server_utils_debian_pkgs }}"
  when: ansible_distribution == 'Ubuntu'
